# Generated by Django 4.0 on 2021-12-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hose',
            new_name='house',
        ),
    ]
