# Generated by Django 4.0 on 2021-12-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_room_alter_room_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_start_date',
            new_name='start_date',
        ),
    ]
