# Generated by Django 4.0 on 2021-12-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOwner',
            new_name='ListingOwner',
        ),
    ]
